### ISSUE TITLE
Merge’s impact on the Ethereum ecosystem

### ISSUE THREAD

**Issue by HoloNine** [Encode-Club-Solidity-Foundations/Lesson-01#34]
Hi @MatheusDaros,

How will the proof-of-stake transition impact the ETH software development? Will ETH development become simpler after the transition to Ethereum WebAssembly, I know that is currently under active development. What are your thoughts?

**Comment by MatheusDaros** [comment]
Hello @wisethee 
Thanks for the question.
For solidity programming, the current developments do not alter the experience directly, since all changes are being applied to the consensus layer. Once the execution layer changes begin, solidity programming could be affected more directly by some changes in the EVM in the near/medium future, but that yet remains to be seen.
