### ISSUE TITLE
Stateless Ethereum

### ISSUE THREAD

**Issue by TomaszWaszczyk** [Encode-Club-Solidity-Foundations/Lesson-01#46]
Do you think that Ethereum will became Stateless? Do you have some up-to-date materials on that?

**Comment by MatheusDaros** [comment]
Hello @TomaszWaszczyk 

Thanks for your question.

If by `Stateless` you mean the delegation of the responsibility of dealing with state to another part, then yes, it is entirely possible. Actually, since the merger we're already running the [execution layer separated to the consensus layer](https://www.alchemy.com/overviews/execution-layer-and-consensus-layer-node-clients). Since the execution layer is now much more safer and easier to upgrade and manage around, it is totally possible that in the near future we could se some development to explore the possibility of a Stateless Ethereum.

**Comment by TomaszWaszczyk** [comment]
Thanks.
